
spring:
  web:
    resources:
      static-locations: classpath:/static/
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: true

app:
  fixed-block-extensions:
  - bat
  - cmd
  - com
  - cpl
  - exe
  - js
  - scr
  max-custom-extension: 200